#! /bin/sh

build_dir=`pwd`
source_dir=`pwd`/..

cd $source_dir &&
autoconf &&

cd $build_dir &&
$source_dir/configure &&
# 注：只保留生成的Makefile，删除其他中间文件
rm -rf $source_dir/{autom4te.cache,configure}
rm -rf $build_dir/{config.log,config.status}

exit $?

